# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 383)
        MainWindow.setMinimumSize(QtCore.QSize(800, 383))
        MainWindow.setMaximumSize(QtCore.QSize(800, 383))
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.callsignGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.callsignGroup.setGeometry(QtCore.QRect(10, 10, 341, 61))
        self.callsignGroup.setObjectName("callsignGroup")
        self.callsignLineEdit = QtWidgets.QLineEdit(self.callsignGroup)
        self.callsignLineEdit.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.callsignLineEdit.setText("")
        self.callsignLineEdit.setObjectName("callsignLineEdit")
        self.saveCallsignButton = QtWidgets.QPushButton(self.callsignGroup)
        self.saveCallsignButton.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.saveCallsignButton.setObjectName("saveCallsignButton")
        self.ccLabel = QtWidgets.QLabel(self.callsignGroup)
        self.ccLabel.setGeometry(QtCore.QRect(216, 10, 111, 20))
        self.ccLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ccLabel.setObjectName("ccLabel")
        self.currentCallsignLabel = QtWidgets.QLabel(self.callsignGroup)
        self.currentCallsignLabel.setGeometry(QtCore.QRect(210, 30, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentCallsignLabel.setFont(font)
        self.currentCallsignLabel.setTextFormat(QtCore.Qt.AutoText)
        self.currentCallsignLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentCallsignLabel.setObjectName("currentCallsignLabel")
        self.sendMessageGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.sendMessageGroup.setGeometry(QtCore.QRect(10, 80, 341, 251))
        self.sendMessageGroup.setObjectName("sendMessageGroup")
        self.sendTab = QtWidgets.QTabWidget(self.sendMessageGroup)
        self.sendTab.setGeometry(QtCore.QRect(10, 20, 321, 221))
        self.sendTab.setObjectName("sendTab")
        self.telexTab = QtWidgets.QWidget()
        self.telexTab.setObjectName("telexTab")
        self.telexRLabel = QtWidgets.QLabel(self.telexTab)
        self.telexRLabel.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.telexRLabel.setObjectName("telexRLabel")
        self.telexMLabel = QtWidgets.QLabel(self.telexTab)
        self.telexMLabel.setGeometry(QtCore.QRect(10, 40, 47, 21))
        self.telexMLabel.setObjectName("telexMLabel")
        self.telexRecipientLine = QtWidgets.QLineEdit(self.telexTab)
        self.telexRecipientLine.setGeometry(QtCore.QRect(70, 10, 231, 20))
        self.telexRecipientLine.setObjectName("telexRecipientLine")
        self.telexMessageBox = QtWidgets.QPlainTextEdit(self.telexTab)
        self.telexMessageBox.setGeometry(QtCore.QRect(70, 40, 231, 111))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.telexMessageBox.setFont(font)
        self.telexMessageBox.setObjectName("telexMessageBox")
        self.telexSendButton = QtWidgets.QPushButton(self.telexTab)
        self.telexSendButton.setGeometry(QtCore.QRect(10, 160, 291, 31))
        self.telexSendButton.setObjectName("telexSendButton")
        self.sendTab.addTab(self.telexTab, "")
        self.infoReqTab = QtWidgets.QWidget()
        self.infoReqTab.setObjectName("infoReqTab")
        self.infoTypeCombo = QtWidgets.QComboBox(self.infoReqTab)
        self.infoTypeCombo.setGeometry(QtCore.QRect(70, 10, 191, 22))
        self.infoTypeCombo.setObjectName("infoTypeCombo")
        self.infoTypeCombo.addItem("")
        self.infoTypeCombo.addItem("")
        self.infoTypeCombo.addItem("")
        self.infoTypeCombo.addItem("")
        self.intoTLabel = QtWidgets.QLabel(self.infoReqTab)
        self.intoTLabel.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.intoTLabel.setObjectName("intoTLabel")
        self.infoTypeHelpButton = QtWidgets.QPushButton(self.infoReqTab)
        self.infoTypeHelpButton.setGeometry(QtCore.QRect(270, 10, 31, 23))
        self.infoTypeHelpButton.setCheckable(False)
        self.infoTypeHelpButton.setAutoDefault(False)
        self.infoTypeHelpButton.setDefault(False)
        self.infoTypeHelpButton.setFlat(False)
        self.infoTypeHelpButton.setObjectName("infoTypeHelpButton")
        self.intoALabel = QtWidgets.QLabel(self.infoReqTab)
        self.intoALabel.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.intoALabel.setObjectName("intoALabel")
        self.infoAirportBox = QtWidgets.QLineEdit(self.infoReqTab)
        self.infoAirportBox.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.infoAirportBox.setMaxLength(4)
        self.infoAirportBox.setFrame(True)
        self.infoAirportBox.setClearButtonEnabled(False)
        self.infoAirportBox.setObjectName("infoAirportBox")
        self.infoSendButton = QtWidgets.QPushButton(self.infoReqTab)
        self.infoSendButton.setGeometry(QtCore.QRect(10, 160, 291, 31))
        self.infoSendButton.setObjectName("infoSendButton")
        self.sendTab.addTab(self.infoReqTab, "")
        self.CPDLCTab = QtWidgets.QWidget()
        self.CPDLCTab.setObjectName("CPDLCTab")
        self.cpdlcReplyHelpButton = QtWidgets.QPushButton(self.CPDLCTab)
        self.cpdlcReplyHelpButton.setGeometry(QtCore.QRect(270, 40, 31, 23))
        self.cpdlcReplyHelpButton.setCheckable(False)
        self.cpdlcReplyHelpButton.setAutoDefault(False)
        self.cpdlcReplyHelpButton.setDefault(False)
        self.cpdlcReplyHelpButton.setFlat(False)
        self.cpdlcReplyHelpButton.setObjectName("cpdlcReplyHelpButton")
        self.cpdlcReplyCombo = QtWidgets.QComboBox(self.CPDLCTab)
        self.cpdlcReplyCombo.setGeometry(QtCore.QRect(70, 40, 191, 22))
        self.cpdlcReplyCombo.setObjectName("cpdlcReplyCombo")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcReplyCombo.addItem("")
        self.cpdlcRepLabel = QtWidgets.QLabel(self.CPDLCTab)
        self.cpdlcRepLabel.setGeometry(QtCore.QRect(10, 30, 47, 41))
        self.cpdlcRepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cpdlcRepLabel.setWordWrap(True)
        self.cpdlcRepLabel.setObjectName("cpdlcRepLabel")
        self.cpdlcRecLabel = QtWidgets.QLabel(self.CPDLCTab)
        self.cpdlcRecLabel.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.cpdlcRecLabel.setObjectName("cpdlcRecLabel")
        self.cpdlcRecipientBox = QtWidgets.QLineEdit(self.CPDLCTab)
        self.cpdlcRecipientBox.setGeometry(QtCore.QRect(70, 10, 231, 20))
        self.cpdlcRecipientBox.setObjectName("cpdlcRecipientBox")
        self.cpdlcSendButton = QtWidgets.QPushButton(self.CPDLCTab)
        self.cpdlcSendButton.setGeometry(QtCore.QRect(10, 160, 291, 31))
        self.cpdlcSendButton.setObjectName("cpdlcSendButton")
        self.cpdlcMessageBox = QtWidgets.QPlainTextEdit(self.CPDLCTab)
        self.cpdlcMessageBox.setGeometry(QtCore.QRect(70, 70, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.cpdlcMessageBox.setFont(font)
        self.cpdlcMessageBox.setObjectName("cpdlcMessageBox")
        self.cpdlcMLabel = QtWidgets.QLabel(self.CPDLCTab)
        self.cpdlcMLabel.setGeometry(QtCore.QRect(10, 70, 47, 21))
        self.cpdlcMLabel.setObjectName("cpdlcMLabel")
        self.cpdlcResponseLabel = QtWidgets.QLabel(self.CPDLCTab)
        self.cpdlcResponseLabel.setGeometry(QtCore.QRect(10, 130, 51, 21))
        self.cpdlcResponseLabel.setObjectName("cpdlcResponseLabel")
        self.cpdlcResponseCheck = QtWidgets.QCheckBox(self.CPDLCTab)
        self.cpdlcResponseCheck.setGeometry(QtCore.QRect(70, 120, 20, 41))
        self.cpdlcResponseCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cpdlcResponseCheck.setText("")
        self.cpdlcResponseCheck.setObjectName("cpdlcResponseCheck")
        self.sendTab.addTab(self.CPDLCTab, "")
        self.messagesGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.messagesGroup.setGeometry(QtCore.QRect(360, 70, 431, 261))
        self.messagesGroup.setObjectName("messagesGroup")
        self.messagesLabel = QtWidgets.QLabel(self.messagesGroup)
        self.messagesLabel.setGeometry(QtCore.QRect(10, 40, 401, 31))
        self.messagesLabel.setObjectName("messagesLabel")
        self.printLastMessageButton = QtWidgets.QPushButton(self.messagesGroup)
        self.printLastMessageButton.setGeometry(QtCore.QRect(320, 20, 101, 23))
        self.printLastMessageButton.setObjectName("printLastMessageButton")
        self.clearMessageLogButton = QtWidgets.QPushButton(self.messagesGroup)
        self.clearMessageLogButton.setGeometry(QtCore.QRect(210, 20, 101, 23))
        self.clearMessageLogButton.setObjectName("clearMessageLogButton")
        self.saveMessageLogButton = QtWidgets.QPushButton(self.messagesGroup)
        self.saveMessageLogButton.setGeometry(QtCore.QRect(100, 20, 101, 23))
        self.saveMessageLogButton.setObjectName("saveMessageLogButton")
        self.messageLogDisplay = QtWidgets.QPlainTextEdit(self.messagesGroup)
        self.messageLogDisplay.setEnabled(True)
        self.messageLogDisplay.setGeometry(QtCore.QRect(10, 70, 411, 181))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.messageLogDisplay.setFont(font)
        self.messageLogDisplay.setAcceptDrops(False)
        self.messageLogDisplay.setReadOnly(True)
        self.messageLogDisplay.setPlainText("")
        self.messageLogDisplay.setObjectName("messageLogDisplay")
        self.connectionGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.connectionGroup.setGeometry(QtCore.QRect(360, 10, 431, 51))
        self.connectionGroup.setObjectName("connectionGroup")
        self.disconnectButton = QtWidgets.QPushButton(self.connectionGroup)
        self.disconnectButton.setEnabled(False)
        self.disconnectButton.setGeometry(QtCore.QRect(180, 20, 161, 23))
        self.disconnectButton.setObjectName("disconnectButton")
        self.connectButton = QtWidgets.QPushButton(self.connectionGroup)
        self.connectButton.setGeometry(QtCore.QRect(10, 20, 161, 23))
        self.connectButton.setObjectName("connectButton")
        self.connectionStatusLabel = QtWidgets.QLabel(self.connectionGroup)
        self.connectionStatusLabel.setGeometry(QtCore.QRect(340, 21, 91, 21))
        self.connectionStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        MainWindow.setCentralWidget(self.MainWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuDropdown = QtWidgets.QMenu(self.menubar)
        self.menuDropdown.setObjectName("menuDropdown")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.settingsMenuAction = QtWidgets.QAction(MainWindow)
        self.settingsMenuAction.setObjectName("settingsMenuAction")
        self.exitMenuAction = QtWidgets.QAction(MainWindow)
        self.exitMenuAction.setObjectName("exitMenuAction")
        self.aboutMenuAction = QtWidgets.QAction(MainWindow)
        self.aboutMenuAction.setObjectName("aboutMenuAction")
        self.menuDropdown.addAction(self.settingsMenuAction)
        self.menuDropdown.addSeparator()
        self.menuDropdown.addAction(self.aboutMenuAction)
        self.menuDropdown.addAction(self.exitMenuAction)
        self.menubar.addAction(self.menuDropdown.menuAction())

        self.retranslateUi(MainWindow)
        self.sendTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACARS"))
        self.callsignGroup.setTitle(_translate("MainWindow", "Callsign"))
        self.saveCallsignButton.setText(_translate("MainWindow", "Save"))
        self.ccLabel.setText(_translate("MainWindow", "Current callsign:"))
        self.currentCallsignLabel.setText(_translate("MainWindow", "Not set"))
        self.sendMessageGroup.setTitle(_translate("MainWindow", "Send message"))
        self.telexRLabel.setText(_translate("MainWindow", "Recipient"))
        self.telexMLabel.setText(_translate("MainWindow", "Message"))
        self.telexSendButton.setText(_translate("MainWindow", "Send"))
        self.sendTab.setTabText(self.sendTab.indexOf(self.telexTab), _translate("MainWindow", "Telex"))
        self.infoTypeCombo.setItemText(0, _translate("MainWindow", "METAR"))
        self.infoTypeCombo.setItemText(1, _translate("MainWindow", "TAF"))
        self.infoTypeCombo.setItemText(2, _translate("MainWindow", "Short TAF"))
        self.infoTypeCombo.setItemText(3, _translate("MainWindow", "VATSIM ATIS"))
        self.intoTLabel.setText(_translate("MainWindow", "Type"))
        self.infoTypeHelpButton.setText(_translate("MainWindow", "?"))
        self.intoALabel.setText(_translate("MainWindow", "Airport"))
        self.infoSendButton.setText(_translate("MainWindow", "Send"))
        self.sendTab.setTabText(self.sendTab.indexOf(self.infoReqTab), _translate("MainWindow", "InfoReq"))
        self.cpdlcReplyHelpButton.setText(_translate("MainWindow", "?"))
        self.cpdlcReplyCombo.setItemText(0, _translate("MainWindow", "None required"))
        self.cpdlcReplyCombo.setItemText(1, _translate("MainWindow", "Yes"))
        self.cpdlcReplyCombo.setItemText(2, _translate("MainWindow", "No"))
        self.cpdlcReplyCombo.setItemText(3, _translate("MainWindow", "Wilco/Unable"))
        self.cpdlcReplyCombo.setItemText(4, _translate("MainWindow", "Affirm/Negative"))
        self.cpdlcReplyCombo.setItemText(5, _translate("MainWindow", "Roger"))
        self.cpdlcRepLabel.setText(_translate("MainWindow", "Reply required"))
        self.cpdlcRecLabel.setText(_translate("MainWindow", "Recipient"))
        self.cpdlcSendButton.setText(_translate("MainWindow", "Send"))
        self.cpdlcMLabel.setText(_translate("MainWindow", "Message"))
        self.cpdlcResponseLabel.setText(_translate("MainWindow", "Response?"))
        self.sendTab.setTabText(self.sendTab.indexOf(self.CPDLCTab), _translate("MainWindow", "CPDLC"))
        self.messagesGroup.setTitle(_translate("MainWindow", "Messages"))
        self.messagesLabel.setText(_translate("MainWindow", "Message log"))
        self.printLastMessageButton.setText(_translate("MainWindow", "Print last message"))
        self.clearMessageLogButton.setText(_translate("MainWindow", "Clear log"))
        self.saveMessageLogButton.setText(_translate("MainWindow", "Save log"))
        self.connectionGroup.setTitle(_translate("MainWindow", "Hoppie connection"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "Disconnected"))
        self.menuDropdown.setTitle(_translate("MainWindow", "Menu"))
        self.settingsMenuAction.setText(_translate("MainWindow", "Settings"))
        self.exitMenuAction.setText(_translate("MainWindow", "Exit"))
        self.aboutMenuAction.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
