# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(398, 300)
        Dialog.setModal(True)
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setEnabled(True)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.tabs.setObjectName("tabs")
        self.printTab = QtWidgets.QWidget()
        self.printTab.setEnabled(True)
        self.printTab.setObjectName("printTab")
        self.printDisableFrame = QtWidgets.QFrame(self.printTab)
        self.printDisableFrame.setEnabled(True)
        self.printDisableFrame.setGeometry(QtCore.QRect(0, 29, 371, 191))
        self.printDisableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.printDisableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.printDisableFrame.setObjectName("printDisableFrame")
        self.printVendorIDLine = QtWidgets.QLineEdit(self.printDisableFrame)
        self.printVendorIDLine.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.printVendorIDLine.setMaxLength(4)
        self.printVendorIDLine.setObjectName("printVendorIDLine")
        self.print0xLabel2 = QtWidgets.QLabel(self.printDisableFrame)
        self.print0xLabel2.setGeometry(QtCore.QRect(70, 40, 21, 21))
        self.print0xLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.print0xLabel2.setObjectName("print0xLabel2")
        self.printTestPushButton = QtWidgets.QPushButton(self.printDisableFrame)
        self.printTestPushButton.setGeometry(QtCore.QRect(220, 20, 141, 31))
        self.printTestPushButton.setObjectName("printTestPushButton")
        self.printProductIDLine = QtWidgets.QLineEdit(self.printDisableFrame)
        self.printProductIDLine.setGeometry(QtCore.QRect(90, 10, 113, 20))
        self.printProductIDLine.setMaxLength(4)
        self.printProductIDLine.setObjectName("printProductIDLine")
        self.printVendorIDLabel = QtWidgets.QLabel(self.printDisableFrame)
        self.printVendorIDLabel.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.printVendorIDLabel.setObjectName("printVendorIDLabel")
        self.print0xLabel = QtWidgets.QLabel(self.printDisableFrame)
        self.print0xLabel.setGeometry(QtCore.QRect(70, 10, 21, 21))
        self.print0xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.print0xLabel.setObjectName("print0xLabel")
        self.printProductIDLabel = QtWidgets.QLabel(self.printDisableFrame)
        self.printProductIDLabel.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.printProductIDLabel.setObjectName("printProductIDLabel")
        self.printAutoPrintNewBox = QtWidgets.QCheckBox(self.printDisableFrame)
        self.printAutoPrintNewBox.setGeometry(QtCore.QRect(10, 80, 181, 17))
        self.printAutoPrintNewBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.printAutoPrintNewBox.setObjectName("printAutoPrintNewBox")
        self.enablePrintBox = QtWidgets.QCheckBox(self.printTab)
        self.enablePrintBox.setGeometry(QtCore.QRect(10, 0, 121, 31))
        self.enablePrintBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.enablePrintBox.setAutoFillBackground(False)
        self.enablePrintBox.setChecked(True)
        self.enablePrintBox.setObjectName("enablePrintBox")
        self.tabs.addTab(self.printTab, "")
        self.hoppieTab = QtWidgets.QWidget()
        self.hoppieTab.setObjectName("hoppieTab")
        self.hoppieLoginLabel = QtWidgets.QLabel(self.hoppieTab)
        self.hoppieLoginLabel.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.hoppieLoginLabel.setObjectName("hoppieLoginLabel")
        self.hoppieLoginCodeLine = QtWidgets.QLineEdit(self.hoppieTab)
        self.hoppieLoginCodeLine.setGeometry(QtCore.QRect(100, 40, 261, 20))
        self.hoppieLoginCodeLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.hoppieLoginCodeLine.setObjectName("hoppieLoginCodeLine")
        self.hoppiePollIntLabel = QtWidgets.QLabel(self.hoppieTab)
        self.hoppiePollIntLabel.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.hoppiePollIntLabel.setObjectName("hoppiePollIntLabel")
        self.hoppiePollIntSpin = QtWidgets.QSpinBox(self.hoppieTab)
        self.hoppiePollIntSpin.setGeometry(QtCore.QRect(100, 70, 42, 22))
        self.hoppiePollIntSpin.setMinimum(5)
        self.hoppiePollIntSpin.setMaximum(60)
        self.hoppiePollIntSpin.setObjectName("hoppiePollIntSpin")
        self.hoppiePollIntSecLabel = QtWidgets.QLabel(self.hoppieTab)
        self.hoppiePollIntSecLabel.setGeometry(QtCore.QRect(150, 70, 47, 21))
        self.hoppiePollIntSecLabel.setObjectName("hoppiePollIntSecLabel")
        self.hoppieServerAddrLabel = QtWidgets.QLabel(self.hoppieTab)
        self.hoppieServerAddrLabel.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.hoppieServerAddrLabel.setObjectName("hoppieServerAddrLabel")
        self.hoppieServerAddrLine = QtWidgets.QLineEdit(self.hoppieTab)
        self.hoppieServerAddrLine.setGeometry(QtCore.QRect(100, 10, 261, 20))
        self.hoppieServerAddrLine.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.hoppieServerAddrLine.setObjectName("hoppieServerAddrLine")
        self.tabs.addTab(self.hoppieTab, "")
        self.audioTab = QtWidgets.QWidget()
        self.audioTab.setObjectName("audioTab")
        self.audioPlaySoundBox = QtWidgets.QCheckBox(self.audioTab)
        self.audioPlaySoundBox.setGeometry(QtCore.QRect(0, 10, 211, 17))
        self.audioPlaySoundBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.audioPlaySoundBox.setObjectName("audioPlaySoundBox")
        self.tabs.addTab(self.audioTab, "")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(10, 270, 381, 23))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ACARS settings"))
        self.print0xLabel2.setText(_translate("Dialog", "0x"))
        self.printTestPushButton.setText(_translate("Dialog", "Run a test print"))
        self.printVendorIDLabel.setText(_translate("Dialog", "Vendor ID"))
        self.print0xLabel.setText(_translate("Dialog", "0x"))
        self.printProductIDLabel.setText(_translate("Dialog", "Product ID"))
        self.printAutoPrintNewBox.setText(_translate("Dialog", "Automatically print new messages"))
        self.enablePrintBox.setText(_translate("Dialog", "Enable POS printing?"))
        self.tabs.setTabText(self.tabs.indexOf(self.printTab), _translate("Dialog", "Print"))
        self.hoppieLoginLabel.setText(_translate("Dialog", "Login code"))
        self.hoppiePollIntLabel.setText(_translate("Dialog", "Poll interval"))
        self.hoppiePollIntSecLabel.setText(_translate("Dialog", "seconds"))
        self.hoppieServerAddrLabel.setText(_translate("Dialog", "Server address"))
        self.hoppieServerAddrLine.setText(_translate("Dialog", "http://www.hoppie.nl/acars/system/connect.html"))
        self.tabs.setTabText(self.tabs.indexOf(self.hoppieTab), _translate("Dialog", "Hoppie"))
        self.audioPlaySoundBox.setText(_translate("Dialog", "Play sound on reciept of new message"))
        self.tabs.setTabText(self.tabs.indexOf(self.audioTab), _translate("Dialog", "Audio"))
        self.saveButton.setText(_translate("Dialog", "Save all settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
